import StoreProvider from '@/redux/provider/StoreProvider.js';
import './globals.css';
import Navbar from '@/components/reuseable/Navbar/Navbar';
import SideBarContainer from '@/components/reuseable/SideBar/SideBarContainer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <SideBarContainer>
            <Navbar />
            {children}
          </SideBarContainer>
        </StoreProvider>
      </body>
    </html>
  );
}
